### ISSUE TITLE
syncing lights

### ISSUE THREAD

**Issue by dcsan** [dcsan/storydata#15]
## lights

> The textual descriptions, icons, and images of lights are not in sync. At the start of the game, 0/4 lights are on. With each task completed, one should come one until all four are completed. 4 lights are not directly related to 6 tasks-- do you think this is confusing? (I don't necessarily think so)

right now 
- task1 = 1 lights
- task2 = 2 lights etc.

But it may get out of sync. it's a bit complicated/messy to track really (one thing i want to clean up with a proper hints/task system). did you notice where it goes out of sync?

or should it be 
- task1 = 0 lights
- task2 = 1 lights

maybe thats why i'm confused
ach task3 is out of sync.
let me know what it should be here and i'll see if we can make a system to fix it.
ideally this would be part of a task list and we'd assign everything in a centralised place, but thats a lot more code.
its just a mess cleaning up scatted across the script.
also i did get confused originally on the counting.

I could make something like `progress: 3` a function that just renders the little progress bar. but then it would be more "fixed"

### task2

![image](https://user-images.githubusercontent.com/514002/98669609-7256d000-2306-11eb-9bd6-28b77d87c4bc.png)

### task3 
yeah looks like this is out of sync
![image](https://user-images.githubusercontent.com/514002/98669921-ccf02c00-2306-11eb-81c7-f616e749aede.png)

### task4

![image](https://user-images.githubusercontent.com/514002/98669843-b2b64e00-2306-11eb-962e-eff0ba93d434.png)

it looks like maybe lights were edited?

![image](https://user-images.githubusercontent.com/514002/98676164-1b55f880-2310-11eb-989b-8b8c96befdc6.png)

**Comment by dcsan** [comment]
lets' discuss this one here, big topic

**Comment by intellikat** [comment]
I think it's prob best to playthrough and test all the lights to see where it isn't syncing up. 

First light should come on when clothes are donned, then proceed from there. There should only be 3 lights on in the dark, but now there is still the old 4 lights image.

Sometimes the image doesn't sync with the icons or the textual description as seen in this one, at the beginning when no lights are on:
 
![Screen Shot 2020-11-10 at 10 46 42 PM](https://user-images.githubusercontent.com/7255631/98691012-8bb05880-23a8-11eb-9482-8fbe768c8409.png)

Another time is here:
 
![Screen Shot 2020-11-10 at 10 48 36 PM](https://user-images.githubusercontent.com/7255631/98691096-9ec32880-23a8-11eb-8f45-f30700182193.png)

**Comment by dcsan** [comment]
you mean

tasks 3/6
img: 2 lights
emoji: 2 lights?

it should be 3 lights?

**Comment by intellikat** [comment]
The "task x/x" is something you coded so I don't want to comment on that. I think your task number is +1 of the lights, but you can check that part to see if it's synced. There's also a difference between "doing task 3" vs. "task 3 completed" since the completion of a puzzle task results in a light coming on.

What I mean is that at any point there are 3 different ways that the number of lights currently on is indicated to the player.

#1 **command "look room"** (jpeg image) (also automatically triggered when entering the room and when the room goes dark)

The proper illustration should always match the state of the lights in the room. The progression is: no lights, 1 light, 2 lights, 3 lights/dark room, 4 lights.

![Screen Shot 2020-11-13 at 8 55 22 AM](https://user-images.githubusercontent.com/7255631/99014830-7eed5980-258e-11eb-9439-4dfb6ac511f4.png)

#2 **command "look lights"** (icon) (also automatically triggered when completing a puzzle task)

You can see in the image here how this is not synced properly as only one light should be on.

![Screen Shot 2020-11-13 at 9 00 37 AM](https://user-images.githubusercontent.com/7255631/99015005-de4b6980-258e-11eb-8c31-b615bb1d6dc0.png)

#3 text descriptions. Any text that described the lights at any point should describe the proper state.

Easiest way is to run through the game and test each of these by "look room" and "look lights" during each state to compare.

**Comment by dcsan** [comment]
this lights thing is very confusing to track. I just need a clear list of what lights go with what and I can fix the story.

enter room - no lights
you get assigned task1 - to get dresssed
on completion 1 light comes on?

so basically at start of task1 = 0 light
at end of task1 => task2 => 1 light

so basically `task[num] - 1`

task1: get dressed => 0 light => complete => 1 light
task2: 1 light exercise => 
task3: 2 lightss wash =>
task4: 3 lights / (dark room) green =>

seems to match:

 [Task 4/6] Three of the green lights are on, and a yellow light seeps through the window.

**Comment by dcsan** [comment]
if that's correct one of us could clean up the script

**Comment by dcsan** [comment]
## task cuts

```

      - name: task1
        imageUrl: bureau/ch1/500/bh-ch1-no-lights.jpg
        short: "`[Task 1/6]` You are in what appears to be a mental patient’s bedroom. \n
          You see a desk, a sink, a window, a door, lights, and a wall covered with images. \n"
        navbar: full

      # repeat room description
      - name: task2
        imageUrl: bureau/ch1/500/bh-ch1-1-light.jpg
        short: "💡 … … …\n
          `[Task 2/6]` You are in what appears to be a mental patient’s bedroom. \n
          You see a desk, a sink, a window, a door, lights, and a wall covered with images.
          \n
          \nOne of the green lights has come on.
          "
        navbar: full

      - name: task3
        imageUrl: bureau/ch1/500/bh-ch1-2-lights.jpg
        short: "💡💡 … …\n
        `[Task 3/6]`
          Two of the green lights are on."
        navbar: full

      - name: task4
        # imageUrl: asylum/rooms/cell-dark.jpg
        # imageUrl: bureau/ch1/500/bh-ch1-3-lights.jpg
        imageUrl: bureau/ch1/500/bh-ch1-4-lights-dark.jpg
        short: "💡💡💡 …\n
          `[Task 4/6]`
          Three of the green lights are on, and a yellow light seeps through the window."
        navbar: full

      - name: task5
        imageUrl: bureau/ch1/500/bh-ch1-4-lights.jpg
        short: "💡💡💡💡\n
          All four of the green lights are on."

```

## lights
```
      - name: lights
        called: wall lights|lightbulbs|lamps
        states:
          - name: default
            short: A vertical row of small green lightbulbs is built into the wall above the sink.
          - name: task1
            short: … … … …
              None of the lights are lit up.
          - name: task2
            short: 💡 … … …
              One of the green lights has come on.
          - name: task3
            short: 💡💡 … …
              Two of the green lights are lit up.
          - name: task4
            short: 💡💡💡 …
              Three of the green lights are lit.
          - name: task5
            short: 💡💡💡💡
              More green lights are lighting up; it seems you're making progress.

```
